from typing import Dict, Any, Optional

"""
Modular Food Knowledge Base for FitVerse AI Nutrition.
Contains typical nutritional vectors (per standard serving/piece or per 100g)
for Indian, Western, vegetarian, vegan, and non-vegetarian foods.
Values are calibrated as estimates (not clinical absolutes).
"""

FOOD_DATABASE: Dict[str, Dict[str, Any]] = {
    # --- Indian Breads & Staples ---
    "roti": {
        "canonical_name": "Roti",
        "aliases": ["rotis", "chapati", "chapatis", "phulka", "fulka"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 100,
        "protein": 3.0,
        "carbs": 20.0,
        "fat": 0.8,
        "fiber": 2.0,
        "category": "bread",
        "diet": "vegan",
    },
    "paratha": {
        "canonical_name": "Paratha",
        "aliases": ["parathas", "aloo paratha", "plain paratha"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 240,
        "protein": 4.5,
        "carbs": 32.0,
        "fat": 11.0,
        "fiber": 3.0,
        "category": "bread",
        "diet": "vegetarian",
    },
    "naan": {
        "canonical_name": "Naan",
        "aliases": ["butter naan", "garlic naan", "plain naan"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 260,
        "protein": 7.5,
        "carbs": 44.0,
        "fat": 5.5,
        "fiber": 2.0,
        "category": "bread",
        "diet": "vegetarian",
    },

    # --- Dals & Lentil Curries ---
    "dal": {
        "canonical_name": "Dal",
        "aliases": ["daal", "dhal", "yellow dal", "dal tadka", "dal fry", "moong dal", "toor dal"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 180,
        "protein": 9.0,
        "carbs": 25.0,
        "fat": 5.0,
        "fiber": 4.0,
        "category": "lentil",
        "diet": "vegan",
    },
    "dal makhani": {
        "canonical_name": "Dal Makhani",
        "aliases": ["maa ki dal"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 280,
        "protein": 10.0,
        "carbs": 28.0,
        "fat": 14.0,
        "fiber": 5.0,
        "category": "lentil",
        "diet": "vegetarian",
    },
    "chole": {
        "canonical_name": "Chole",
        "aliases": ["chana masala", "chickpea curry", "chhole"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 240,
        "protein": 11.0,
        "carbs": 34.0,
        "fat": 7.0,
        "fiber": 6.5,
        "category": "legume",
        "diet": "vegan",
    },
    "rajma": {
        "canonical_name": "Rajma",
        "aliases": ["kidney beans curry"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 230,
        "protein": 12.0,
        "carbs": 35.0,
        "fat": 5.5,
        "fiber": 7.0,
        "category": "legume",
        "diet": "vegan",
    },

    # --- Rice & Grains ---
    "rice": {
        "canonical_name": "Rice",
        "aliases": ["white rice", "steamed rice", "boiled rice", "chawal"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 205,
        "protein": 4.2,
        "carbs": 45.0,
        "fat": 0.5,
        "fiber": 0.6,
        "category": "grain",
        "diet": "vegan",
    },
    "brown rice": {
        "canonical_name": "Brown Rice",
        "aliases": ["whole grain rice"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 215,
        "protein": 5.0,
        "carbs": 44.0,
        "fat": 1.8,
        "fiber": 3.5,
        "category": "grain",
        "diet": "vegan",
    },
    "biryani": {
        "canonical_name": "Chicken Biryani",
        "aliases": ["chicken biryani", "biriyani", "murgh biryani"],
        "default_unit": "plate",
        "default_quantity": 1.0,
        "calories": 520,
        "protein": 28.0,
        "carbs": 62.0,
        "fat": 16.0,
        "fiber": 3.0,
        "category": "mixed",
        "diet": "non-vegetarian",
    },
    "veg biryani": {
        "canonical_name": "Veg Biryani",
        "aliases": ["vegetable biryani", "veg pulao", "pulao"],
        "default_unit": "plate",
        "default_quantity": 1.0,
        "calories": 380,
        "protein": 8.0,
        "carbs": 60.0,
        "fat": 12.0,
        "fiber": 4.5,
        "category": "mixed",
        "diet": "vegetarian",
    },
    "khichdi": {
        "canonical_name": "Khichdi",
        "aliases": ["khichri", "dal khichdi"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 260,
        "protein": 9.5,
        "carbs": 46.0,
        "fat": 4.0,
        "fiber": 4.0,
        "category": "grain",
        "diet": "vegetarian",
    },
    "poha": {
        "canonical_name": "Poha",
        "aliases": ["kanda poha", "flattened rice"],
        "default_unit": "plate",
        "default_quantity": 1.0,
        "calories": 250,
        "protein": 4.5,
        "carbs": 44.0,
        "fat": 6.5,
        "fiber": 2.5,
        "category": "breakfast",
        "diet": "vegan",
    },
    "oats": {
        "canonical_name": "Oatmeal",
        "aliases": ["oat", "oatmeal", "porridge", "rolled oats"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 240,
        "protein": 10.0,
        "carbs": 40.0,
        "fat": 4.5,
        "fiber": 6.0,
        "category": "breakfast",
        "diet": "vegan",
    },

    # --- Dairy & Plant Proteins ---
    "paneer": {
        "canonical_name": "Paneer",
        "aliases": ["cottage cheese", "paneer tikka", "raw paneer"],
        "default_unit": "g",
        "default_quantity": 100.0,
        # Normalized per 100g
        "calories": 296,
        "protein": 18.3,
        "carbs": 3.4,
        "fat": 22.5,
        "fiber": 0.0,
        "category": "dairy",
        "diet": "vegetarian",
    },
    "tofu": {
        "canonical_name": "Tofu",
        "aliases": ["bean curd", "soya paneer"],
        "default_unit": "g",
        "default_quantity": 100.0,
        "calories": 144,
        "protein": 17.3,
        "carbs": 2.8,
        "fat": 8.7,
        "fiber": 2.3,
        "category": "plant_protein",
        "diet": "vegan",
    },
    "curd": {
        "canonical_name": "Curd (Dahi)",
        "aliases": ["dahi", "plain yogurt", "yoghurt"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 120,
        "protein": 6.5,
        "carbs": 8.0,
        "fat": 7.0,
        "fiber": 0.0,
        "category": "dairy",
        "diet": "vegetarian",
    },
    "greek yogurt": {
        "canonical_name": "Greek Yogurt",
        "aliases": ["hung curd"],
        "default_unit": "cup",
        "default_quantity": 1.0,
        "calories": 130,
        "protein": 15.0,
        "carbs": 6.0,
        "fat": 4.0,
        "fiber": 0.0,
        "category": "dairy",
        "diet": "vegetarian",
    },
    "milk": {
        "canonical_name": "Milk",
        "aliases": ["dairy milk", "cow milk", "glass of milk"],
        "default_unit": "glass",
        "default_quantity": 1.0,
        "calories": 140,
        "protein": 7.5,
        "carbs": 11.0,
        "fat": 7.0,
        "fiber": 0.0,
        "category": "dairy",
        "diet": "vegetarian",
    },

    # --- Poultry, Meat & Eggs ---
    "egg": {
        "canonical_name": "Boiled Egg",
        "aliases": ["eggs", "boiled egg", "boiled eggs", "anda"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 78,
        "protein": 6.3,
        "carbs": 0.6,
        "fat": 5.3,
        "fiber": 0.0,
        "category": "poultry",
        "diet": "non-vegetarian",
    },
    "omelette": {
        "canonical_name": "Omelette",
        "aliases": ["omlet", "egg omelette", "scrambled eggs"],
        "default_unit": "serving",
        "default_quantity": 1.0,
        "calories": 190,
        "protein": 13.0,
        "carbs": 1.5,
        "fat": 14.0,
        "fiber": 0.0,
        "category": "poultry",
        "diet": "non-vegetarian",
    },
    "chicken breast": {
        "canonical_name": "Grilled Chicken Breast",
        "aliases": ["chicken", "grilled chicken", "boiled chicken"],
        "default_unit": "g",
        "default_quantity": 100.0,
        "calories": 165,
        "protein": 31.0,
        "carbs": 0.0,
        "fat": 3.6,
        "fiber": 0.0,
        "category": "poultry",
        "diet": "non-vegetarian",
    },
    "chicken curry": {
        "canonical_name": "Chicken Curry",
        "aliases": ["murgh curry", "chicken gravy"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 320,
        "protein": 26.0,
        "carbs": 8.0,
        "fat": 20.0,
        "fiber": 1.5,
        "category": "poultry",
        "diet": "non-vegetarian",
    },
    "fish": {
        "canonical_name": "Fish Curry / Grilled Fish",
        "aliases": ["grilled fish", "fish fry", "salmon"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 220,
        "protein": 24.0,
        "carbs": 2.0,
        "fat": 12.0,
        "fiber": 0.0,
        "category": "seafood",
        "diet": "non-vegetarian",
    },
    "whey protein": {
        "canonical_name": "Whey Protein Shake",
        "aliases": ["whey", "protein shake", "protein scoop"],
        "default_unit": "scoop",
        "default_quantity": 1.0,
        "calories": 130,
        "protein": 25.0,
        "carbs": 3.0,
        "fat": 1.5,
        "fiber": 0.5,
        "category": "supplement",
        "diet": "vegetarian",
    },

    # --- Fruits & Vegetables ---
    "banana": {
        "canonical_name": "Banana",
        "aliases": ["bananas", "kela"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 105,
        "protein": 1.3,
        "carbs": 27.0,
        "fat": 0.3,
        "fiber": 3.1,
        "category": "fruit",
        "diet": "vegan",
    },
    "apple": {
        "canonical_name": "Apple",
        "aliases": ["apples", "seb"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 95,
        "protein": 0.5,
        "carbs": 25.0,
        "fat": 0.3,
        "fiber": 4.4,
        "category": "fruit",
        "diet": "vegan",
    },
    "salad": {
        "canonical_name": "Green Salad",
        "aliases": ["cucumber salad", "mixed salad", "kachumber"],
        "default_unit": "bowl",
        "default_quantity": 1.0,
        "calories": 45,
        "protein": 1.8,
        "carbs": 8.5,
        "fat": 0.5,
        "fiber": 3.2,
        "category": "vegetable",
        "diet": "vegan",
    },

    # --- South Indian ---
    "idli": {
        "canonical_name": "Idli",
        "aliases": ["idlis", "steamed idli"],
        "default_unit": "piece",
        "default_quantity": 2.0,
        "calories": 130,
        "protein": 4.0,
        "carbs": 26.0,
        "fat": 0.8,
        "fiber": 1.8,
        "category": "breakfast",
        "diet": "vegan",
    },
    "dosa": {
        "canonical_name": "Plain Dosa",
        "aliases": ["masala dosa", "crispy dosa"],
        "default_unit": "piece",
        "default_quantity": 1.0,
        "calories": 210,
        "protein": 4.5,
        "carbs": 32.0,
        "fat": 7.0,
        "fiber": 2.0,
        "category": "breakfast",
        "diet": "vegetarian",
    },
}

def lookup_food_item(query: str) -> Optional[Dict[str, Any]]:
    """
    Looks up a food query against canonical names and aliases.
    """
    clean = query.strip().lower()
    
    # 1. Exact canonical key match
    if clean in FOOD_DATABASE:
        return FOOD_DATABASE[clean]
        
    # 2. Match against aliases
    for key, item in FOOD_DATABASE.items():
        if clean == key or clean in item.get("aliases", []):
            return item
            
    # 3. Substring match
    for key, item in FOOD_DATABASE.items():
        if key in clean or any(alias in clean for alias in item.get("aliases", [])):
            return item
            
    return None
